name: Main

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
      - ".gitignore"
      - "LICENSE"
    branches:
      - master
    tags:
      - "**"
  pull_request:
    paths-ignore:
      - "*.md"
      - ".gitignore"
      - "LICENSE"
    branches:
      - master

jobs:
  lint:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          components: clippy,rustfmt
      - run: make lint

  test:
    needs: [lint]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
      - name: Install podman 4.3.1
        run: |
          echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
          sudo apt -y update
          sudo apt -y install podman=4:4.3.1-0ubuntu22.04+obs64.10
      - name: Start podman
        run: |
          systemctl restart --user podman
          systemctl restart --user podman.socket
      - name: Test
        run: |
          podman pull ubuntu:latest
          make test
